# Generated by Django 4.2.11 on 2026-03-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Assembly", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cao_assemblies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("event_number", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("payload", models.JSONField(default=dict)),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("aggregate_type", models.CharField(max_length=50)),
                ("is_reverted", models.BooleanField(default=False)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cao_event_store",
                "ordering": ["event_number"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cao_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cao_projects",
            },
        ),
        migrations.CreateModel(
            name="Sketch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Sketch", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("geometry_data", models.JSONField(default=dict)),
                ("constraints", models.JSONField(default=list)),
                ("plane", models.CharField(default="XY", max_length=10)),
                ("offset_z", models.FloatField(default=0.0)),
                ("is_valid", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sketches",
                        to="cao_core.project",
                    ),
                ),
            ],
            options={
                "db_table": "cao_sketches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_type", models.CharField(max_length=100)),
                ("operation_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("undo_index", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cao_core.eventstore",
                    ),
                ),
                (
                    "last_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cao_core.eventstore",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_history",
                        to="cao_core.project",
                    ),
                ),
            ],
            options={
                "db_table": "cao_operation_history",
                "ordering": ["-undo_index"],
            },
        ),
        migrations.CreateModel(
            name="Geometry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Geometry", max_length=255)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("sketch", "Sketch (2D)"),
                            ("extrude", "Extrusion"),
                            ("pocket", "Pocket"),
                            ("fillet", "Fillet"),
                            ("chamfer", "Chamfer"),
                            ("thread", "Thread"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "step_file",
                    models.FileField(
                        blank=True, null=True, upload_to="geometry_models/"
                    ),
                ),
                (
                    "stl_file",
                    models.FileField(
                        blank=True, null=True, upload_to="geometry_models/"
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("bounding_box", models.JSONField(default=dict)),
                ("is_valid", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_sketch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geometries_created",
                        to="cao_core.sketch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geometries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_geometry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cao_core.geometry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometries",
                        to="cao_core.project",
                    ),
                ),
            ],
            options={
                "db_table": "cao_geometries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="eventstore",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="cao_core.project",
            ),
        ),
        migrations.CreateModel(
            name="CollaborationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("session_token", models.CharField(max_length=255, unique=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_sessions",
                        to="cao_core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cao_collaboration_sessions",
            },
        ),
        migrations.CreateModel(
            name="AssemblyPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_x", models.FloatField(default=0.0)),
                ("position_y", models.FloatField(default=0.0)),
                ("position_z", models.FloatField(default=0.0)),
                ("rotation_x", models.FloatField(default=0.0)),
                ("rotation_y", models.FloatField(default=0.0)),
                ("rotation_z", models.FloatField(default=0.0)),
                ("scale", models.FloatField(default=1.0)),
                ("part_number", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="cao_core.assembly",
                    ),
                ),
                (
                    "geometry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cao_core.geometry",
                    ),
                ),
            ],
            options={
                "db_table": "cao_assembly_parts",
                "ordering": ["part_number"],
            },
        ),
        migrations.AddField(
            model_name="assembly",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="cao_core.project",
            ),
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("aggregate_type", models.CharField(max_length=50)),
                ("event_number", models.BigIntegerField()),
                ("state", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="cao_core.project",
                    ),
                ),
            ],
            options={
                "db_table": "cao_snapshots",
                "indexes": [
                    models.Index(
                        fields=["aggregate_id", "event_number"],
                        name="cao_snapsho_aggrega_2b6f03_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sketch",
            index=models.Index(
                fields=["project", "created_at"], name="cao_sketche_project_665ea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "created_at"], name="cao_project_owner_i_49c295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationhistory",
            index=models.Index(
                fields=["project", "undo_index"], name="cao_operati_project_2ea194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geometry",
            index=models.Index(
                fields=["project", "operation_type"],
                name="cao_geometr_project_0b7ec2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geometry",
            index=models.Index(
                fields=["base_sketch"], name="cao_geometr_base_sk_0ec9f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geometry",
            index=models.Index(
                fields=["parent_geometry"], name="cao_geometr_parent__a31f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventstore",
            index=models.Index(
                fields=["project", "event_number"],
                name="cao_event_s_project_c8ee31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventstore",
            index=models.Index(
                fields=["aggregate_id", "aggregate_type"],
                name="cao_event_s_aggrega_926c79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventstore",
            index=models.Index(
                fields=["timestamp"], name="cao_event_s_timesta_b431c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventstore",
            unique_together={("project", "event_number")},
        ),
        migrations.AddIndex(
            model_name="collaborationsession",
            index=models.Index(
                fields=["project", "is_active"], name="cao_collabo_project_71c647_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assemblypart",
            unique_together={("assembly", "geometry")},
        ),
    ]
